### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by AxartInc** [lycee-chaptal-sii/colin-marion-arthur-eyad#5]
@atrantan 
Pouvez-vous upload la présentation latex du projet ci jointe dans le fichier docs afin de garder une trace du  projet complet, car nous n'avons plus l'autorisation de push.
Merci

[index.pdf](https://github.com/lycee-chaptal-sii/colin-marion-arthur-eyad/files/2059076/index.pdf)

**Comment by atrantan** [comment]
@AxartInc ok
